// ---------------------------------------------------------------------------
// Dev fixture
// ---------------------------------------------------------------------------
// The database `npm run dev:server` runs against (./data/dev): several fake
// households of deliberately different shapes, with real logins, so day-to-day
// development exercises the paths a single open household never reaches —
// household switching, roles, invites, a non-GBP currency, a non-monthly budget
// period, a one-person household.
//
// It is NOT the demo dataset: demo mode stays one open, password-less household
// (src/server/db/demo.ts), because a demo you have to log into is a bad demo.
// Both are generated by the same builder; this file only says who lives where.
//
// Every account shares DEV_PASSWORD — this database is disposable fake data and
// never leaves the machine. The seeder refuses any target that looks like the
// real database (scripts/demo-guard.ts).
// ---------------------------------------------------------------------------

import { inArray } from 'drizzle-orm'
import { hashToken } from '../auth/bearer'
import { hashPassword } from '../auth/password'
import { DEFAULT_HOUSEHOLD_ID, type Role } from '../trpc/tenant'
import { newId } from '../../shared/ids'
import type { DB } from './client'
import { buildDemoData, MAPLE_STREET, seedHouseholds, type DemoDataset, type DemoHouseholdSpec } from './demo'
import { setAuthRequired, setInstanceOwnerId } from './instanceSettings'
import { household, rateLimit } from './schema'

/** The password every dev account is seeded with. Meets the real policy, so
 *  changing it through the UI behaves the same as it would in production. */
export const DEV_PASSWORD = 'hearth-dev'

/** The account to log in as: owner of the primary household, and a member of the
 *  other two, so the household switcher has somewhere to go. */
export const DEV_LOGIN = 'ava'

/** The raw token behind the seeded pending invitation — open
 *  http://localhost:5173/invite#<this> to walk the accept flow. */
export const DEV_INVITE_TOKEN = 'dev-invite-token'

export const DEV_HOUSEHOLD_IDS = {
  /** The instance's primary household: unauthenticated requests fall back to it,
   *  and instance-wide actions are refused elsewhere, so it must be this id. */
  maple: DEFAULT_HOUSEHOLD_ID,
  ivy: 'dev-ivy-cottage',
  harbour: 'dev-harbour-view',
} as const

/** The three fake households, in the order the seeder inserts them. `now` is
 *  passed in because the four-weekly period needs an anchor date relative to it. */
function devHouseholds(now: Date): DemoHouseholdSpec[] {
  const anchorYear = now.getFullYear() - 1
  const fourWeeklyAnchor = `${anchorYear}-${(now.getMonth() + 1).toString().padStart(2, '0')}-01`

  return [
    {
      // The demo household, with a couple of years of history behind it.
      ...MAPLE_STREET,
      scale: { spendMonths: 24, payslipMonths: 24, netWorthMonths: 24, spendVolume: 1.5 },
    },
    {
      // One person, no joint split to speak of, and a four-weekly budget period.
      id: DEV_HOUSEHOLD_IDS.ivy,
      displayName: 'Ivy Cottage',
      rent: 875,
      settings: {
        budgetPeriodFrequency: 'four_weekly',
        budgetPeriodAnchor: fourWeeklyAnchor,
        emergencyFundMonths: 6,
      },
      scale: { spendMonths: 18, payslipMonths: 18, netWorthMonths: 18, costFactor: 0.8 },
      people: [
        {
          key: 'priya',
          name: 'Priya',
          color: 'orange',
          salary: 34000,
          promotedTo: 39500,
          positions: ['Ward Nurse', 'Senior Ward Nurse'],
          baselineMonthsAgo: 20,
          promotionMonthsAgo: 4,
          commute: 'car',
          studentLoan: true,
          pension: { institution: 'NHS Pension', start: 26800, monthly: 410 },
          sideIncome: { name: 'Bank shifts', amount: 240, basis: 'gross', recurrence: 'monthly', note: 'Varies month to month' },
          payees: ['Sports Direct', 'The Works', 'Superdrug', 'Wilko'],
        },
      ],
    },
    {
      // Euros, a payday budget period, and joint costs funded from a shared pool.
      id: DEV_HOUSEHOLD_IDS.harbour,
      displayName: 'Harbour View',
      rent: 1180,
      settings: {
        currencyCode: 'EUR',
        currencySymbol: '€',
        currencySymbolPosition: 'suffix',
        currencyGroupSeparator: '.',
        currencyDecimalSeparator: ',',
        locale: 'fi-FI',
        budgetPeriodStartDay: 25,
        jointFundingModel: 'pooled',
        jointContributionBasis: 'income_proportional',
      },
      scale: { spendMonths: 12, payslipMonths: 12, netWorthMonths: 12, spendVolume: 1.2, costFactor: 1.1 },
      people: [
        {
          key: 'mikko',
          name: 'Mikko',
          color: 'indigo',
          salary: 52000,
          positions: ['Marine Engineer', 'Lead Marine Engineer'],
          baselineMonthsAgo: 18,
          promotionMonthsAgo: 3,
          commute: 'rail',
          isa: true,
          pension: { institution: 'Ilmarinen', start: 31200, monthly: 480 },
          payees: ['Verkkokauppa', 'Stockmann', 'Clas Ohlson'],
        },
        {
          key: 'sara',
          name: 'Sara',
          color: 'pink',
          salary: 46000,
          positions: ['Radiographer', 'Senior Radiographer'],
          baselineMonthsAgo: 15,
          promotionMonthsAgo: 2,
          commute: 'none',
          pension: { institution: 'Varma', start: 24100, monthly: 400 },
          sideIncome: { name: 'Photography', amount: 180, basis: 'gross', recurrence: 'monthly' },
          payees: ['Zalando', 'Sokos', 'Kirjakauppa'],
        },
      ],
    },
  ]
}

interface DevMembership {
  householdId: string
  role: Role
  /** Budgeting member (by display name) to link the account to, if any. */
  person?: string
}

interface DevUserSpec {
  username: string
  displayName: string
  email: string | null
  /** Whether the address has been proven — password reset only mails a proven one. */
  emailVerified?: boolean
  memberships: DevMembership[]
}

const DEV_USERS: DevUserSpec[] = [
  {
    // The login to use. Owner of the primary household, and carries a different
    // role in each of the other two so role gating is visible by switching.
    username: DEV_LOGIN,
    displayName: 'Ava Whitfield',
    email: 'ava@example.com',
    emailVerified: true,
    memberships: [
      { householdId: DEV_HOUSEHOLD_IDS.maple, role: 'owner', person: 'Ava' },
      { householdId: DEV_HOUSEHOLD_IDS.harbour, role: 'admin' },
      { householdId: DEV_HOUSEHOLD_IDS.ivy, role: 'member' },
    ],
  },
  {
    username: 'ben',
    displayName: 'Ben Whitfield',
    email: 'ben@example.com',
    memberships: [{ householdId: DEV_HOUSEHOLD_IDS.maple, role: 'member', person: 'Ben' }],
  },
  {
    // A viewer with no budgeting member of their own — read-only, owns nothing.
    username: 'nan',
    displayName: 'Nan',
    email: null,
    memberships: [{ householdId: DEV_HOUSEHOLD_IDS.maple, role: 'viewer' }],
  },
  {
    username: 'priya',
    displayName: 'Priya Raman',
    email: 'priya@example.com',
    emailVerified: true,
    memberships: [{ householdId: DEV_HOUSEHOLD_IDS.ivy, role: 'owner', person: 'Priya' }],
  },
  {
    username: 'mikko',
    displayName: 'Mikko Laine',
    email: 'mikko@example.com',
    memberships: [{ householdId: DEV_HOUSEHOLD_IDS.harbour, role: 'owner', person: 'Mikko' }],
  },
]

export interface DevSeedOptions {
  /** Reference "now" (epoch millis). Defaults to Date.now(). Anchors all trends. */
  now?: number
  /** Base PRNG seed; each household gets its own offset from it. */
  seed?: number
}

/** Find a generated member row by display name, so an account can be linked to
 *  the person it belongs to. */
function findMember(dataset: DemoDataset, displayName: string): Record<string, unknown> | undefined {
  return (dataset.rows['member'] ?? []).find((m) => m['displayName'] === displayName)
}

/**
 * Wipe every table and insert the dev fixture: three households, five accounts
 * and a pending invitation, all locked behind {@link DEV_PASSWORD}. Meant to run
 * against ./data/dev (see scripts/seed-dev.ts), never the real database.
 * Returns a per-table row count.
 */
export async function seedDev(db: DB, opts: DevSeedOptions = {}): Promise<Record<string, number>> {
  const now = new Date(opts.now ?? Date.now())
  const baseSeed = opts.seed ?? 0x44455620 // "DEV "

  const datasets: DemoDataset[] = devHouseholds(now).map((spec, i) => ({
    householdId: spec.id,
    // A seed of its own per household: generated ids draw on the PRNG, so a
    // shared seed would mint the same ids twice and collide on insert.
    rows: buildDemoData({ now: now.getTime(), seed: baseSeed + i * 7919, household: spec }),
  }))
  const byHousehold = new Map(datasets.map((d) => [d.householdId, d]))

  // One hash for every account: they all share DEV_PASSWORD, and scrypt is
  // deliberately slow enough that hashing the same string five times is waste.
  const passwordHash = await hashPassword(DEV_PASSWORD)

  const users: Array<Record<string, unknown>> = []
  const memberships: Array<Record<string, unknown>> = []
  let ownerUserId = ''
  for (const spec of DEV_USERS) {
    const userId = newId()
    users.push({
      id: userId,
      username: spec.username,
      email: spec.email,
      displayName: spec.displayName,
      passwordHash,
      emailVerifiedAt: spec.emailVerified ? now : null,
      mfaSecret: null,
      mfaEnabledAt: null,
      mfaRecoveryCodes: null,
      mfaLastStep: null,
      onboardingDismissedAt: now, // past the first-run checklist
      createdAt: now,
      updatedAt: now,
    })
    for (const m of spec.memberships) {
      memberships.push({
        id: newId(),
        userId,
        householdId: m.householdId,
        role: m.role,
        invitedAt: now,
        acceptedAt: now,
        createdAt: now,
        updatedAt: now,
      })
      if (m.householdId === DEFAULT_HOUSEHOLD_ID && m.role === 'owner') ownerUserId = userId

      // Link the account to its budgeting member, where it has one.
      const dataset = byHousehold.get(m.householdId)
      const person = m.person && dataset ? findMember(dataset, m.person) : undefined
      if (person) person['userId'] = userId
    }
  }

  // A pending invitation to the primary household — the access screen lists it,
  // and /invite#DEV_INVITE_TOKEN walks the accept flow. `memberId` stays null:
  // `invitation` is inserted before `member`, so it can't reference one yet.
  const invitations = [
    {
      id: newId(),
      tokenHash: hashToken(DEV_INVITE_TOKEN),
      householdId: DEV_HOUSEHOLD_IDS.maple,
      role: 'member',
      email: 'newcomer@example.com',
      memberId: null,
      invitedByUserId: ownerUserId,
      createdAt: now,
      expiresAt: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000),
      acceptedAt: null,
    },
  ]

  // The identity rows ride along with the primary household's dataset. Each one
  // carries its own householdId where it has a column for it, so they land in the
  // right household rather than the dataset's.
  const primary = datasets[0]!
  primary.rows['user'] = users
  primary.rows['membership'] = memberships
  primary.rows['invitation'] = invitations

  const counts = await seedHouseholds(db, datasets)

  // instance_settings sits outside the wipe (it's instance-, not household-scoped),
  // so a re-seed would otherwise leave ownerUserId pointing at a deleted account.
  await setInstanceOwnerId(db, ownerUserId)
  await setAuthRequired(db, true)
  // Login lockouts are instance-level too — clear them so a re-seed is a clean slate.
  await db.delete(rateLimit)

  return counts
}

/** True if the dev fixture is already seeded (used to avoid re-seeding on every
 *  `tsx watch` restart). Checks every household, not just the primary one, so a
 *  database seeded with demo data is topped up rather than half-used. */
export async function hasDevData(db: DB): Promise<boolean> {
  const ids = Object.values(DEV_HOUSEHOLD_IDS)
  const rows = await db.select().from(household).where(inArray(household.id, ids))
  return rows.length === ids.length && rows.every((h) => h.setupCompletedAt != null)
}
