/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AccountsRouteImport } from "./routes/accounts";
import { Route as CatchupRouteImport } from "./routes/catchup";
import { Route as CategoriesRouteImport } from "./routes/categories";
import { Route as FundingRouteImport } from "./routes/funding";
import { Route as ImportRouteImport } from "./routes/import";
import { Route as IncomeRouteImport } from "./routes/income";
import { Route as OutgoingsRouteImport } from "./routes/outgoings";
import { Route as PayslipsRouteImport } from "./routes/payslips";
import { Route as PotsRouteImport } from "./routes/pots";
import { Route as RaisesRouteImport } from "./routes/raises";
import { Route as ReportsRouteImport } from "./routes/reports";
import { Route as ReviewRouteImport } from "./routes/review";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as SpendingRouteImport } from "./routes/spending";
import { Route as UpcomingRouteImport } from "./routes/upcoming";
import { Route as SettingsIndexRouteImport } from "./routes/settings.index";
import { Route as SettingsAccountRouteImport } from "./routes/settings.account";
import { Route as SettingsHouseholdRouteImport } from "./routes/settings.household";
import { Route as SettingsSystemRouteImport } from "./routes/settings.system";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AccountsRoute = AccountsRouteImport.update({
  id: "/accounts",
  path: "/accounts",
  getParentRoute: () => rootRouteImport,
} as any);
const CatchupRoute = CatchupRouteImport.update({
  id: "/catchup",
  path: "/catchup",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesRoute = CategoriesRouteImport.update({
  id: "/categories",
  path: "/categories",
  getParentRoute: () => rootRouteImport,
} as any);
const FundingRoute = FundingRouteImport.update({
  id: "/funding",
  path: "/funding",
  getParentRoute: () => rootRouteImport,
} as any);
const ImportRoute = ImportRouteImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => rootRouteImport,
} as any);
const IncomeRoute = IncomeRouteImport.update({
  id: "/income",
  path: "/income",
  getParentRoute: () => rootRouteImport,
} as any);
const OutgoingsRoute = OutgoingsRouteImport.update({
  id: "/outgoings",
  path: "/outgoings",
  getParentRoute: () => rootRouteImport,
} as any);
const PayslipsRoute = PayslipsRouteImport.update({
  id: "/payslips",
  path: "/payslips",
  getParentRoute: () => rootRouteImport,
} as any);
const PotsRoute = PotsRouteImport.update({
  id: "/pots",
  path: "/pots",
  getParentRoute: () => rootRouteImport,
} as any);
const RaisesRoute = RaisesRouteImport.update({
  id: "/raises",
  path: "/raises",
  getParentRoute: () => rootRouteImport,
} as any);
const ReportsRoute = ReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => rootRouteImport,
} as any);
const ReviewRoute = ReviewRouteImport.update({
  id: "/review",
  path: "/review",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const SpendingRoute = SpendingRouteImport.update({
  id: "/spending",
  path: "/spending",
  getParentRoute: () => rootRouteImport,
} as any);
const UpcomingRoute = UpcomingRouteImport.update({
  id: "/upcoming",
  path: "/upcoming",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsHouseholdRoute = SettingsHouseholdRouteImport.update({
  id: "/household",
  path: "/household",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: "/system",
  path: "/system",
  getParentRoute: () => SettingsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/accounts": typeof AccountsRoute;
  "/catchup": typeof CatchupRoute;
  "/categories": typeof CategoriesRoute;
  "/funding": typeof FundingRoute;
  "/import": typeof ImportRoute;
  "/income": typeof IncomeRoute;
  "/outgoings": typeof OutgoingsRoute;
  "/payslips": typeof PayslipsRoute;
  "/pots": typeof PotsRoute;
  "/raises": typeof RaisesRoute;
  "/reports": typeof ReportsRoute;
  "/review": typeof ReviewRoute;
  "/settings": typeof SettingsRouteWithChildren;
  "/spending": typeof SpendingRoute;
  "/upcoming": typeof UpcomingRoute;
  "/settings/account": typeof SettingsAccountRoute;
  "/settings/household": typeof SettingsHouseholdRoute;
  "/settings/system": typeof SettingsSystemRoute;
  "/settings/": typeof SettingsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/accounts": typeof AccountsRoute;
  "/catchup": typeof CatchupRoute;
  "/categories": typeof CategoriesRoute;
  "/funding": typeof FundingRoute;
  "/import": typeof ImportRoute;
  "/income": typeof IncomeRoute;
  "/outgoings": typeof OutgoingsRoute;
  "/payslips": typeof PayslipsRoute;
  "/pots": typeof PotsRoute;
  "/raises": typeof RaisesRoute;
  "/reports": typeof ReportsRoute;
  "/review": typeof ReviewRoute;
  "/spending": typeof SpendingRoute;
  "/upcoming": typeof UpcomingRoute;
  "/settings/account": typeof SettingsAccountRoute;
  "/settings/household": typeof SettingsHouseholdRoute;
  "/settings/system": typeof SettingsSystemRoute;
  "/settings": typeof SettingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/accounts": typeof AccountsRoute;
  "/catchup": typeof CatchupRoute;
  "/categories": typeof CategoriesRoute;
  "/funding": typeof FundingRoute;
  "/import": typeof ImportRoute;
  "/income": typeof IncomeRoute;
  "/outgoings": typeof OutgoingsRoute;
  "/payslips": typeof PayslipsRoute;
  "/pots": typeof PotsRoute;
  "/raises": typeof RaisesRoute;
  "/reports": typeof ReportsRoute;
  "/review": typeof ReviewRoute;
  "/settings": typeof SettingsRouteWithChildren;
  "/spending": typeof SpendingRoute;
  "/upcoming": typeof UpcomingRoute;
  "/settings/account": typeof SettingsAccountRoute;
  "/settings/household": typeof SettingsHouseholdRoute;
  "/settings/system": typeof SettingsSystemRoute;
  "/settings/": typeof SettingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/accounts"
    | "/catchup"
    | "/categories"
    | "/funding"
    | "/import"
    | "/income"
    | "/outgoings"
    | "/payslips"
    | "/pots"
    | "/raises"
    | "/reports"
    | "/review"
    | "/settings"
    | "/spending"
    | "/upcoming"
    | "/settings/account"
    | "/settings/household"
    | "/settings/system"
    | "/settings/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/accounts"
    | "/catchup"
    | "/categories"
    | "/funding"
    | "/import"
    | "/income"
    | "/outgoings"
    | "/payslips"
    | "/pots"
    | "/raises"
    | "/reports"
    | "/review"
    | "/spending"
    | "/upcoming"
    | "/settings/account"
    | "/settings/household"
    | "/settings/system"
    | "/settings";
  id:
    | "__root__"
    | "/"
    | "/accounts"
    | "/catchup"
    | "/categories"
    | "/funding"
    | "/import"
    | "/income"
    | "/outgoings"
    | "/payslips"
    | "/pots"
    | "/raises"
    | "/reports"
    | "/review"
    | "/settings"
    | "/spending"
    | "/upcoming"
    | "/settings/account"
    | "/settings/household"
    | "/settings/system"
    | "/settings/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AccountsRoute: typeof AccountsRoute;
  CatchupRoute: typeof CatchupRoute;
  CategoriesRoute: typeof CategoriesRoute;
  FundingRoute: typeof FundingRoute;
  ImportRoute: typeof ImportRoute;
  IncomeRoute: typeof IncomeRoute;
  OutgoingsRoute: typeof OutgoingsRoute;
  PayslipsRoute: typeof PayslipsRoute;
  PotsRoute: typeof PotsRoute;
  RaisesRoute: typeof RaisesRoute;
  ReportsRoute: typeof ReportsRoute;
  ReviewRoute: typeof ReviewRoute;
  SettingsRoute: typeof SettingsRouteWithChildren;
  SpendingRoute: typeof SpendingRoute;
  UpcomingRoute: typeof UpcomingRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/accounts": {
      id: "/accounts";
      path: "/accounts";
      fullPath: "/accounts";
      preLoaderRoute: typeof AccountsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/catchup": {
      id: "/catchup";
      path: "/catchup";
      fullPath: "/catchup";
      preLoaderRoute: typeof CatchupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/categories": {
      id: "/categories";
      path: "/categories";
      fullPath: "/categories";
      preLoaderRoute: typeof CategoriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/funding": {
      id: "/funding";
      path: "/funding";
      fullPath: "/funding";
      preLoaderRoute: typeof FundingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/import": {
      id: "/import";
      path: "/import";
      fullPath: "/import";
      preLoaderRoute: typeof ImportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/income": {
      id: "/income";
      path: "/income";
      fullPath: "/income";
      preLoaderRoute: typeof IncomeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/outgoings": {
      id: "/outgoings";
      path: "/outgoings";
      fullPath: "/outgoings";
      preLoaderRoute: typeof OutgoingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/payslips": {
      id: "/payslips";
      path: "/payslips";
      fullPath: "/payslips";
      preLoaderRoute: typeof PayslipsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pots": {
      id: "/pots";
      path: "/pots";
      fullPath: "/pots";
      preLoaderRoute: typeof PotsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/raises": {
      id: "/raises";
      path: "/raises";
      fullPath: "/raises";
      preLoaderRoute: typeof RaisesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports": {
      id: "/reports";
      path: "/reports";
      fullPath: "/reports";
      preLoaderRoute: typeof ReportsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/review": {
      id: "/review";
      path: "/review";
      fullPath: "/review";
      preLoaderRoute: typeof ReviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/spending": {
      id: "/spending";
      path: "/spending";
      fullPath: "/spending";
      preLoaderRoute: typeof SpendingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/upcoming": {
      id: "/upcoming";
      path: "/upcoming";
      fullPath: "/upcoming";
      preLoaderRoute: typeof UpcomingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/account": {
      id: "/settings/account";
      path: "/account";
      fullPath: "/settings/account";
      preLoaderRoute: typeof SettingsAccountRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/household": {
      id: "/settings/household";
      path: "/household";
      fullPath: "/settings/household";
      preLoaderRoute: typeof SettingsHouseholdRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/system": {
      id: "/settings/system";
      path: "/system";
      fullPath: "/settings/system";
      preLoaderRoute: typeof SettingsSystemRouteImport;
      parentRoute: typeof SettingsRoute;
    };
  }
}

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute;
  SettingsHouseholdRoute: typeof SettingsHouseholdRoute;
  SettingsSystemRoute: typeof SettingsSystemRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsHouseholdRoute: SettingsHouseholdRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  CatchupRoute: CatchupRoute,
  CategoriesRoute: CategoriesRoute,
  FundingRoute: FundingRoute,
  ImportRoute: ImportRoute,
  IncomeRoute: IncomeRoute,
  OutgoingsRoute: OutgoingsRoute,
  PayslipsRoute: PayslipsRoute,
  PotsRoute: PotsRoute,
  RaisesRoute: RaisesRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SpendingRoute: SpendingRoute,
  UpcomingRoute: UpcomingRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
